Because there is a bug with the release and the structure of the project, we moved the source in apps/fubar. By the way we fix the release and avoid to receive this kind of error:
ERROR: generate failed while processing fubar/rel:
{'EXIT',{{badmatch,{error,"fubar: Application version clash. Multiple directories contain version \"3.0.0\"."}},

Move the application fubar in its own apps/fubar directory.